# ワークフローの名前、Actions上に表示される
name: ipaをAppStoreとFirebase Distributionにあげる
on: push

jobs:
  main:
    runs-on: macOS-latest
    env:
      KEYCHAIN: '/Library/Keychains/System.keychain'
      ASC_KEY_ID: C538N5NKPK
      ASC_ISSUER_ID: def67d36-9a40-4ec1-a18e-f0b94bf3c072

    steps:
      - run: echo "${{ secrets.P8_APPSTORECONNECT_API }}"